### PR TITLE
Improved CI/Test process and secret creation bug fix

### PR DESCRIPTION
**Pull request by patrickleet**
I rewrote most of the CI, using a lot from what was there, but I wanted it to be modular so it could be used for running locally more easily as well.

I also rewrote the example with working example, and changed the retry rate to much quicker cause I often sit and wait for my CI to create keycloak resources and this would save me time frequently.

Finally, I found the fix in PR #41 is insufficient, and replaced with more direct translation of example of creating secrets from docs.

Verified working locally, and by running the github action via `act`

### CODE REVIEW

**Comment by patrickleet** [comment]
Woo, it worked!

Shaves 3 minutes off the build time, too!

I'll rebase to cleanup the commit history and add back in some more Kubernetes versions!

**Review by axdotl — APPROVED** [review]
That's awesome work! Thanks a lot!

**Review by monotek — APPROVED** [review]

**Comment by patrickleet** [comment]
@monotek @axdotl ah I need to update the deploy script to reflect these changes too!

https://github.com/kiwigrid/keycloak-controller/runs/1310294487

I'll make a PR shortly.

**Comment by patrickleet** [comment]
https://github.com/kiwigrid/keycloak-controller/pull/43

**Pull request merged**
