### PR TITLE
feat(keycloak): upgrade keycloak from 9 to 11

### PR DESCRIPTION
**Pull request by patrickleet**
BREAKING CHANGE: Major version change of Keycloak

### CODE REVIEW

**Comment by patrickleet** [comment]
https://www.keycloak.org/docs/latest/release_notes/

**Comment by patrickleet** [comment]
I did not test this manually, just let CI run

**Comment by patrickleet** [comment]
any updates on this @rpahli?

**Comment by axdotl** [comment]
Hi @patrickleet, we're thinking about how to verify that this and upcoming changes of keycloak major versions will be downward compatible. So we've to create an integration test setup which allows us to test with different keycloak versions.
That's why we're currently slow on this issue.

**Comment by patrickleet** [comment]
No worries - using 9 for now - thanks for the project! I'm subscribed to the issue :)

**Comment by patrickleet** [comment]
any updates @axdotl ?

**Comment by monotek** [comment]
@axdotl is not working for @kiwigrid anymore.
I guess we have to wait for @rpahli to jump in.

**Comment by monotek** [comment]
@patrickleet 
I've started to implement some tests in https://github.com/kiwigrid/keycloak-controller/pull/27.
Needs some work though.
Could yo uplease rebase and update to keycloak 11?

**Comment by patrickleet** [comment]
rebased and updated! I see lot's of new tests, good job!

**Comment by monotek** [comment]
Damn, i forgot that we can't use docker secrets in pull requests :/
Have to look for a workaround and also improve the last test...

**Comment by monotek** [comment]
@patrickleet pat

I've fixed the docker problem.
Please rebase again.

I talk to @rpahli tomorrow, if we want to test other stuff too...

**Comment by patrickleet** [comment]
@monotek done

**Review by rpahli — APPROVED** [review]
LGTM

**Pull request merged**
